// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exewbbilppsujfxmsvik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4ZXdiYmlscHBzdWpmeG1zdmlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzM5OTQsImV4cCI6MjA2OTM0OTk5NH0.sPH11UA1_RWYmh46baHkRC7O4DYaylj4nxAa8ghVRyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});